dist: trusty
sudo: required

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt562-trusty --yes
    - sudo apt-get update
    - sudo apt-get install -qq qt5-qmake qt56base

script:
    - source /opt/qt56/bin/qt56-env.sh
    - /opt/qt56/bin/qmake
    - make

after_success:
    - ./ffparser --cfg test_data/case1/case1.cfg --source test_data/case1/case1.source
    - ./ffparser --cfg test_data/case2/case2.cfg --source test_data/case2/case2.source
    - ./ffparser --cfg test_data/case3/case3.cfg --source test_data/case3/case3.source
    - ./ffparser --cfg test_data/case4/case4.cfg --source test_data/case4/case4.source
    - ./ffparser --cfg test_data/case5/case5.cfg --source test_data/case5/case5.source
